#!/usr/bin/env bash
#

echo "Starting server process..."
# TODO: Add case statement to allow stopping, starting, and restarting
# TODO: Add logic to detect both podman and docker, if both are installed, use podman as default "first found"
# TODO: Move to RHEL image

# Check if podman exists, otherwise use docker
CONTAINER_CMD="docker"
if command -v podman &> /dev/null; then
    CONTAINER_CMD="podman"
fi
$CONTAINER_CMD run -d --rm --name showroom-httpd -p 8443:80 -v "./www:/usr/local/apache2/htdocs/" docker.io/httpd:2.4
echo "Serving lab content on http://localhost:8443/index.html"
