#!/usr/bin/env bash
#

echo "Stopping serve process..."
# Check if podman exists, otherwise use docker
CONTAINER_CMD="docker"
if command -v podman &> /dev/null; then
    CONTAINER_CMD="podman"
fi
$CONTAINER_CMD kill showroom-httpd
echo "Stopped serve process."
