#!/usr/bin/env bash
#

echo "Starting build process..."
echo "Removing old site..."
rm -rf ./www/*

echo "Building new site..."
# Check if podman exists, otherwise use docker
CONTAINER_CMD="docker"
if command -v podman &> /dev/null; then
    CONTAINER_CMD="podman"
fi
$CONTAINER_CMD run --rm --name showroom-builder --platform linux/amd64 -v "./:/antora" docker.io/antora/antora site.yml
cp ./ui-config.yml ./www/

 if test -f "/tmp/nookbag.zip"; then
    echo "UI already downloaded."
else
    echo "Downloding UI..."
    wget -q https://github.com/rhpds/nookbag/releases/download/nookbag-v0.0.4/nookbag-v0.0.4.zip -O /tmp/nookbag.zip 
fi

tar -xf /tmp/nookbag.zip -C ./www/

echo "Build process complete. Check the ./www folder for the generated site."

echo "To view the site locally, run the following command: utilities/serve.sh"
echo "If already running then browse to http://localhost:8443/index.html"
